name: Deploy NuGet Package

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Auto versioning
      run: echo ::set-env name=VERSION::$(date +%Y%m%d)$(git log --format=%h -1) >> $GITHUB_ENV

    - name: Switch directory
      run: cd Devity.${{ inputs.PROJECT_NAME }}

    - name: Build and test
      run: | 
        dotnet build --configuration Release
        dotnet test --configuration Release --no-build
      
    - name: Package
      run: dotnet pack --configuration Release --no-build --output nupkgs --version ${{ env.VERSION }}

    - name: Deploy
      run: |
        ls
        dotnet nuget push nupkgs/Devity.${{ inputs.PROJECT_NAME }}.${{ env.VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json