name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: devitysw/Devity/.github/workflows/run-tests.yml@main

  publish-blazor:
    uses: devitysw/Devity/.github/workflows/publish-package.yml@main
    needs: run-tests
    with:
      PROJECT_NAME: 'Blazor'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  publish-extensions:
    uses: devitysw/Devity/.github/workflows/publish-package.yml@main
    needs: run-tests
    with:
      PROJECT_NAME: 'Extensions'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  publish-mailing:
    uses: devitysw/Devity/.github/workflows/publish-package.yml@main
    needs: run-tests
    with:
      PROJECT_NAME: 'Mailing'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  publish-payout:
    uses: devitysw/Devity/.github/workflows/publish-package.yml@main
    needs: run-tests
    with:
      PROJECT_NAME: 'Payout'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}