name: Deploy NuGet Package

on:
  push:
    branches:
      - master

jobs:
  deploy-blazor:
    uses: devitysw/Devity/.github/workflows/deploy-package.yml@master
    with:
      PROJECT_NAME: 'Blazor'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  deploy-extensions:
    uses: devitysw/Devity/.github/workflows/deploy-package.yml@master
    with:
      PROJECT_NAME: 'Extensions'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}