name: Deploy NuGet Package

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: devitysw/Devity/.github/workflows/deploy-package.yml@master
      with:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}