name: Deploy NuGet Package

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Use reusable workflow
      uses: devitysw/Devity/deploy-package.yml@master
      with:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}