name: Deploy NuGet Package

on:
  push:
    branches:
      - master

jobs:
  initialize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

  deploy-blazor:
    uses: devitysw/Devity/.github/workflows/deploy-package.yml@master
    needs: initialize
    with:
      PROJECT_NAME: 'Blazor'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  deploy-extensions:
    uses: devitysw/Devity/.github/workflows/deploy-package.yml@master
    needs: initialize
    with:
      PROJECT_NAME: 'Extensions'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}