name: Deploy NuGet Package

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: devitysw/Devity/.github/workflows/deploy-package.yml@master
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}