name: Deploy NuGet Package

on:
  push:
    branches:
      - master

jobs:
  deploy-extensions:
    runs-on: ubuntu-latest
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name: Deploy Devity.Extensions
      uses: devitysw/Devity/deploy-package.yml@master
      with:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        PROJECT_NAME: 'Extensions'

  deploy-blazor:
    runs-on: ubuntu-latest
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name: Deploy Devity.Blazor
      uses: devitysw/Devity/deploy-package.yml@master
      with:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        PROJECT_NAME: 'Blazor'