name: Deploy NuGet Package

on:
  push:
    branches:
      - master

jobs:
  deploy-blazor:
    uses: devitysw/Devity/.github/workflows/deploy-package.yml@master
    with:
      PROJECT_NAME: 'Blazor'

  deploy-extensions:
    uses: devitysw/Devity/.github/workflows/deploy-package.yml@master
    with:
      PROJECT_NAME: 'Extensions'