name: Publish NuGet Package

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string
    secrets:
      NUGET_API_KEY:
        required: true
  workflow_dispatch:
    inputs:
      PROJECT_NAME:
        required: true
        type: choice
        options:
          - Blazor
          - Extensions
          - Mailing
          - Payout

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build and test
      working-directory: ./Devity.${{ inputs.PROJECT_NAME }}
      run: | 
        dotnet build --configuration Release
        dotnet test --configuration Release --no-build
      
    - name: Package
      working-directory: ./Devity.${{ inputs.PROJECT_NAME }}
      run: dotnet pack --configuration Release --no-build

    - name: Publish
      working-directory: ./Devity.${{ inputs.PROJECT_NAME }}
      run: |
        cd bin
        ls
        dotnet nuget push */*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json