name: Publish NuGet Package

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Build and test
      working-directory: ./Devity.Tests
      run: | 
        dotnet build --configuration Release
        dotnet test --configuration Release --no-build